name: Docker Image CI

on:
  push:
    branches: [ "pavans" ]
  pull_request:
    branches: [ "pavans" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/build-push-action@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
